name: flutter_maps
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.1.0 <3.0.0"
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  google_maps_flutter: ^2.0.3
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  font_awesome_flutter: ^9.0.0
  firebase_core: ^1.0.3
  location: ^4.1.1
  # flutter_facebook_login: ^3.0.0
  local_auth: ^1.1.4
  flutter_secure_storage: ^4.1.0  
  http: ^0.13.1
  flutter_screenutil: ^5.0.0
  animated_theme_switcher: ^2.0.1-nullsafety.0
  line_awesome_flutter: ^1.1.0-nullsafety
  provider: ^5.0.0
  image_picker: ^0.7.4
  get_it: ^6.1.1
  firebase_storage: ^8.0.3
  geoflutterfire: ^3.0.0-nullsafety.2
  geolocator: ^7.0.3
  # flutter_ble_lib: ^2.3.0
  flutter_blue: ^0.8.0
  permission_handler: ^6.1.3
  flutter_launcher_icons: ^0.9.0
  convert: ^3.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  percent_indicator: ^3.0.1
  lottie: ^1.0.1
  # flutter_barcode_scanner: ^1.0.2
  firebase_messaging: ^9.1.1
  connectivity: ^3.0.3
  flutter_compass: ^0.6.0
  google_sign_in: ^5.0.2
  google_fonts: ^2.0.0
  get: ^4.1.4
  flutter_spinkit: ^5.0.0
  get_storage: ^2.0.2
  geocoding: ^2.0.0
  flutter_google_places: ^0.3.0
  flutter_colorpicker: ^0.4.0
  flutter_facebook_auth: ^3.3.2+2

  mapbox_gl:
    git: 
      url: git://github.com/morvagergely/flutter-mapbox-gl.git

  flutter_barcode_scanner:
    git:
      url: git://github.com/AmolGangadhare/flutter_barcode_scanner.git
      ref: nullsafety
  flutter_ble_lib:
    git:
      url: git://github.com/privatdoktor/FlutterBleLib.git
      ref: nullsafety

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    android: true
    ios: true
    image_path_android: "assets/icon/icon.png"
    image_path_ios: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/car_icon.png
    - assets/images/Bailey.png
    - assets/images/dog.png
    - assets/images/pin.jpg
    - assets/images/dogpin.png
    - assets/images/markeruser.png
    - assets/images/markeruser1.png
    - assets/images/wifi1.png
    - assets/images/wifi2.png
    - assets/images/wifi3.png
    - assets/images/Bailey1.png
    - assets/images/splash.jpg
    - assets/images/round_marker.png
    - assets/images/direction_arrow.png
    - assets/images/dogpin_green.png
    - assets/images/dogpin_orange.png
    - assets/images/dogpin_red.png
    - assets/images/dogpin_purple.png
    - assets/images/help.png
    - assets/lottie/devs.jpg
    - assets/lottie/powered_by.png
    - assets/icon/icon.png
    - assets/lottie/lottie_file.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 600
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
